#!/usr/bin/env bash
# Generated by Containerization Assist using AI
# -----------------------------------------------------------------------------
# setup-azure-auth-for-pipeline.sh
#
# Creates a User-assigned Managed Identity and configures GitLab OIDC federated
# credentials so the GitLab CI/CD pipeline can authenticate to Azure without
# storing any secrets.
#
# Usage:
#   chmod +x setup-azure-auth-for-pipeline.sh
#   ./setup-azure-auth-for-pipeline.sh
#
# Prerequisites:
#   - Azure CLI installed and logged in (az login)
#   - Sufficient permissions to create identities and assign RBAC roles
# -----------------------------------------------------------------------------
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
# Edit these values before running the script.
SUBSCRIPTION_ID=""                        # Your Azure Subscription ID
IDENTITY_RESOURCE_GROUP="rg-photoalbum-cicd"   # Separate RG for the identity
IDENTITY_NAME="id-photoalbum-gitlab-cicd"
IDENTITY_LOCATION="eastus"

# Resource groups that hold your AKS clusters (space-separated)
AKS_RESOURCE_GROUPS=("rg-photoalbum-dev" "rg-photoalbum-staging" "rg-photoalbum-prod")

# Azure Container Registry resource group
ACR_RESOURCE_GROUP="rg-photoalbum-shared"
ACR_NAME=""                               # Your ACR name (without .azurecr.io)

# GitLab project details
GITLAB_INSTANCE="https://gitlab.com"      # Change for self-hosted GitLab
GITLAB_PROJECT_PATH="<group-or-username>/<project>"  # e.g. myorg/photoalbum

# Branches/environments to issue federated credentials for
ENVIRONMENTS=("dev" "staging" "production")
BRANCH="main"
# ── End Configuration ──────────────────────────────────────────────────────────

echo "==> Setting active subscription: $SUBSCRIPTION_ID"
az account set --subscription "$SUBSCRIPTION_ID"

# 1. Create a dedicated resource group for the managed identity
echo "==> Creating resource group: $IDENTITY_RESOURCE_GROUP"
az group create \
  --name "$IDENTITY_RESOURCE_GROUP" \
  --location "$IDENTITY_LOCATION" \
  --output none

# 2. Create the User-assigned Managed Identity
echo "==> Creating User-assigned Managed Identity: $IDENTITY_NAME"
az identity create \
  --name "$IDENTITY_NAME" \
  --resource-group "$IDENTITY_RESOURCE_GROUP" \
  --location "$IDENTITY_LOCATION" \
  --output none

IDENTITY_CLIENT_ID=$(az identity show \
  --name "$IDENTITY_NAME" \
  --resource-group "$IDENTITY_RESOURCE_GROUP" \
  --query clientId -o tsv)

IDENTITY_PRINCIPAL_ID=$(az identity show \
  --name "$IDENTITY_NAME" \
  --resource-group "$IDENTITY_RESOURCE_GROUP" \
  --query principalId -o tsv)

IDENTITY_ID=$(az identity show \
  --name "$IDENTITY_NAME" \
  --resource-group "$IDENTITY_RESOURCE_GROUP" \
  --query id -o tsv)

TENANT_ID=$(az account show --query tenantId -o tsv)

echo "   Client ID  : $IDENTITY_CLIENT_ID"
echo "   Principal  : $IDENTITY_PRINCIPAL_ID"
echo "   Tenant ID  : $TENANT_ID"

# 3. Configure federated credentials for each GitLab environment
echo "==> Configuring federated credentials for GitLab OIDC..."

for ENV in "${ENVIRONMENTS[@]}"; do
  CRED_NAME="gitlab-${ENV}"
  SUBJECT="project_path:${GITLAB_PROJECT_PATH}:environment:${ENV}"

  echo "   -> Federated credential for environment '$ENV' (subject: $SUBJECT)"
  az identity federated-credential create \
    --identity-name "$IDENTITY_NAME" \
    --resource-group "$IDENTITY_RESOURCE_GROUP" \
    --name "$CRED_NAME" \
    --issuer "${GITLAB_INSTANCE}" \
    --subject "$SUBJECT" \
    --audiences "api://AzureADTokenExchange" \
    --output none
done

# Also add a federated credential for the default branch (for push-triggered jobs)
BRANCH_SUBJECT="project_path:${GITLAB_PROJECT_PATH}:ref_type:branch:ref:${BRANCH}"
echo "   -> Federated credential for branch '$BRANCH' (subject: $BRANCH_SUBJECT)"
az identity federated-credential create \
  --identity-name "$IDENTITY_NAME" \
  --resource-group "$IDENTITY_RESOURCE_GROUP" \
  --name "gitlab-branch-${BRANCH}" \
  --issuer "${GITLAB_INSTANCE}" \
  --subject "$BRANCH_SUBJECT" \
  --audiences "api://AzureADTokenExchange" \
  --output none

# 4. Assign Contributor role on each AKS resource group
echo "==> Assigning Contributor role on AKS resource groups..."
for RG in "${AKS_RESOURCE_GROUPS[@]}"; do
  echo "   -> $RG"
  az role assignment create \
    --assignee "$IDENTITY_PRINCIPAL_ID" \
    --role "Contributor" \
    --scope "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RG}" \
    --output none
done

# 5. Assign AcrPush role on the Container Registry
echo "==> Assigning AcrPush role on ACR: $ACR_NAME"
ACR_ID=$(az acr show \
  --name "$ACR_NAME" \
  --resource-group "$ACR_RESOURCE_GROUP" \
  --query id -o tsv)

az role assignment create \
  --assignee "$IDENTITY_PRINCIPAL_ID" \
  --role "AcrPush" \
  --scope "$ACR_ID" \
  --output none

# 6. Print the GitLab CI/CD variables to configure
echo ""
echo "============================================================"
echo " Add the following variables in GitLab:"
echo " Settings > CI/CD > Variables"
echo "============================================================"
echo " AZURE_CLIENT_ID       = $IDENTITY_CLIENT_ID"
echo " AZURE_TENANT_ID       = $TENANT_ID"
echo " AZURE_SUBSCRIPTION_ID = $SUBSCRIPTION_ID"
echo " ACR_NAME              = $ACR_NAME"
echo ""
echo " Per-environment AKS variables (set as environment-scoped):"
echo " AKS_CLUSTER_NAME_DEV           = <your-dev-aks-cluster-name>"
echo " AKS_RESOURCE_GROUP_DEV         = <your-dev-aks-resource-group>"
echo " AKS_CLUSTER_NAME_STAGING       = <your-staging-aks-cluster-name>"
echo " AKS_RESOURCE_GROUP_STAGING     = <your-staging-aks-resource-group>"
echo " AKS_CLUSTER_NAME_PRODUCTION    = <your-production-aks-cluster-name>"
echo " AKS_RESOURCE_GROUP_PRODUCTION  = <your-production-aks-resource-group>"
echo "============================================================"
